language: python
install:
  - pip install --use-mirrors nose pep8 pylint flake8 coveralls
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4
script:
  - pep8 pinyin.py pinyin_test.py
  - pylint --rcfile=.pylintrc pinyin.py
  - pylint --rcfile=.pylintrc --disable=missing-docstring,invalid-name pinyin_test.py
  - flake8 --max-complexity 7 pinyin.py pinyin_test.py
  - nosetests --with-coverage
after_success:
  - coveralls
